server:
  port: 9003
spring:
  application:
    name: tensquare-qa
  jpa:
      database: mysql
      show-sql: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.46.130:3306/tensquare_qa?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 2000
